# Generated by Django 3.0.8 on 2020-08-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableDemoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dataTable',
            new_name='dataTables',
        ),
    ]
